# -*- coding: utf-8 -*-
"""clean_step2_tableau_prep

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kF7umjIRg0L33KTaD4GJ3HWCYZsY-1hk
"""

"""
Step 2 cleaning: takes the already-cleaned jobs_clean.xlsx (output of
scrape_digital_marketing_jobs.py) and prepares it for Tableau.

pyarrow is needed to write .parquet - already installed in Colab by default,
if not: !pip install pyarrow --quiet

Saves both .parquet (preferred - keeps exact data types, no Excel guessing)
and .xlsx (fallback, in case your Tableau version can't open Parquet).
"""

import re
import pandas as pd

INPUT_PATH = "jobs_clean.xlsx"          # upload this file to Colab first

OUTPUT_WIDE_PARQUET = "jobs_tableau.parquet"        # main table, one row per job
OUTPUT_WIDE_XLSX = "jobs_tableau.xlsx"              # same table, Excel fallback
OUTPUT_SKILLS_PARQUET = "jobs_skills_long.parquet"  # one row per (job, skill)
OUTPUT_SKILLS_XLSX = "jobs_skills_long.xlsx"        # same table, Excel fallback

# ---------------------------------------------------------------------------
# STEP 1. LOAD
# ---------------------------------------------------------------------------

df = pd.read_excel(INPUT_PATH)
print(f"Loaded: {len(df)} rows")

# ---------------------------------------------------------------------------
# STEP 2. REMOVE OFF-TOPIC NOISE
# ---------------------------------------------------------------------------
# The API's full-text search on keywords like "SEA" also matches unrelated
# postings where "sea"/"See" appears as an ordinary word (shipping, cruises,
# aviation maintenance) rather than as the marketing abbreviation. This is a
# narrow, targeted exclusion list - not a broad relevance filter - so it
# only removes postings that are clearly a different industry, and leaves
# any borderline marketing-adjacent role in the dataset.
NOISE_PATTERN = re.compile(
    r"seefracht|kreuzfahrt|chef de partie|bodengerätetechnik|mechaniker(?:in)?\b|"
    r"hotelfachkraft|freight forwarder|pflegefachkraft|fluggerät|karosserie",
    re.IGNORECASE,
)
is_noise = df["titel"].astype(str).str.contains(NOISE_PATTERN)
print(f"Removing {is_noise.sum()} off-topic postings (industry mismatch, mostly from the 'SEA' keyword)")
df = df[~is_noise].copy()

# ---------------------------------------------------------------------------
# STEP 3. STRONGER DUPLICATE REMOVAL
# ---------------------------------------------------------------------------
# The earlier dedup (exact employer + exact title) misses near-duplicates
# where only spacing or gender markers differ, e.g. "Sales Manager*in
# (m/w/d)" vs "Sales Manager (m/w/d)" from the same company. Normalize
# before comparing, and keep the most recently published copy.


def normalize_title(text):
    text = str(text).lower()
    text = re.sub(r"\(m/w/d\)|\(w/m/d\)|\(m/w/x\)|\(gn\)|\*in(nen)?", "", text)
    text = re.sub(r"[^a-z0-9äöüß]+", " ", text)
    return text.strip()


df["_titel_norm"] = df["titel"].apply(normalize_title)
df["_arbeitgeber_norm"] = df["arbeitgeber"].astype(str).str.lower().str.strip()
df["_published_dt"] = pd.to_datetime(df["published"], errors="coerce")

df = df.sort_values("_published_dt", ascending=False)
dedup_key = df["_arbeitgeber_norm"] + "||" + df["_titel_norm"]
before = len(df)
df = df[~dedup_key.duplicated(keep="first")]
print(f"Removing {before - len(df)} additional near-duplicate postings")

df = df.drop(columns=["_titel_norm", "_arbeitgeber_norm"])

# ---------------------------------------------------------------------------
# STEP 4. FILL MISSING VALUES (so Tableau doesn't show blank/Null bins)
# ---------------------------------------------------------------------------

df["city"] = df["city"].fillna("Not specified")
df["zip"] = df["zip"].fillna("Not specified")
df["bundesland"] = df["bundesland"].fillna("Not specified")
df["level"] = df["level"].fillna("Not specified")
if "employment_type" in df.columns:
    df["employment_type"] = df["employment_type"].fillna("None detected")
df["hard_skills"] = df["hard_skills"].fillna("None detected")
df["soft_skills"] = df["soft_skills"].fillna("None detected")

# ---------------------------------------------------------------------------
# STEP 5. FIX DATA TYPES FOR A CLEAN TABLEAU IMPORT
# ---------------------------------------------------------------------------

# real datetime type, not a text string - lets Tableau do date hierarchies
# (year / month / week) automatically, and this is what actually survives
# a parquet round-trip without losing its type
df["published"] = df["_published_dt"]
df = df.drop(columns="_published_dt")

# zip must stay text - as a number it would drop leading zeros (e.g. 08062)
# and Tableau would treat it as a measure instead of a geographic dimension
df["zip"] = df["zip"].astype(str)

# these are categories, not free text - makes filters/legends in Tableau tidy
for col in ["level", "employment_type", "bundesland", "_keyword"]:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip()

# refnr is an identifier, not a number (it contains letters, e.g.
# "10000-1203829266-S") - force it to text explicitly so Tableau never
# treats it as a measure or tries to sum/average it
df["refnr"] = df["refnr"].astype(str)

print(f"\nFinal wide table: {len(df)} rows")
df.to_parquet(OUTPUT_WIDE_PARQUET, index=False, engine="pyarrow")
df.to_excel(OUTPUT_WIDE_XLSX, index=False, engine="openpyxl")
print(f"Saved: {OUTPUT_WIDE_PARQUET} (use this one in Tableau) and {OUTPUT_WIDE_XLSX} (fallback)")

# ---------------------------------------------------------------------------
# STEP 6. BUILD A LONG SKILLS TABLE (one row per job x skill)
# ---------------------------------------------------------------------------
# hard_skills / soft_skills are comma-separated text in the wide table -
# fine for a tooltip, but Tableau can't easily count "how many postings
# mention SEO" from a comma list. This long table has one row per skill
# mention, which makes a skill-frequency bar chart a simple drag-and-drop.

def explode_skills(df, column, skill_type):
    rows = df[["refnr", "titel", "arbeitgeber", "bundesland", "level", column]].copy()
    rows["refnr"] = rows["refnr"].astype(str)
    rows = rows[rows[column] != "Not specified"]
    rows[column] = rows[column].str.split(", ")
    rows = rows.explode(column)
    rows = rows.rename(columns={column: "skill"})
    rows["skill_type"] = skill_type
    return rows


skills_long = pd.concat([
    explode_skills(df, "hard_skills", "Hard Skill"),
    explode_skills(df, "soft_skills", "Soft Skill"),
], ignore_index=True)

print(f"Skills long table: {len(skills_long)} rows")
skills_long.to_parquet(OUTPUT_SKILLS_PARQUET, index=False, engine="pyarrow")
skills_long.to_excel(OUTPUT_SKILLS_XLSX, index=False, engine="openpyxl")
print(f"Saved: {OUTPUT_SKILLS_PARQUET} (use this one in Tableau) and {OUTPUT_SKILLS_XLSX} (fallback)")