# -*- coding: utf-8 -*-
"""scrape_digital_marketing_jobs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nj4-8dUmtpMhVyS292pzsd9Jx7vdhZbo
"""

"""
Collect and clean Digital Marketing job postings from the official
Bundesagentur fuer Arbeit Jobsuche API.

Run in Google Colab. Requires only 'requests', 'pandas' and 'openpyxl'
(all already installed in Colab by default).
"""

import base64
import time
import re
import requests
import pandas as pd

# ---------------------------------------------------------------------------
# CONFIG
# ---------------------------------------------------------------------------

# The Bundesagentur fuer Arbeit Jobsuche API has no official public
# registration process. The client credentials below are the ones published
# in the API's own OpenAPI spec / reference client (bundesAPI/jobsuche-api)
# and are meant to be used exactly like this by any client.
HEADERS = {
    "User-Agent": "Jobsuche/2.9.2 (de.arbeitsagentur.jobboerse; build:1077; iOS 15.1.0) Alamofire/5.4.4",
    "Host": "rest.arbeitsagentur.de",
    "X-API-Key": "jobboerse-jobsuche",
    "Connection": "keep-alive",
}

BASE_URL = "https://rest.arbeitsagentur.de/jobboerse/jobsuche-service"
SEARCH_URL = f"{BASE_URL}/pc/v6/jobs"  # current search endpoint (v4/app/jobs was retired)
DETAILS_URL = f"{BASE_URL}/pc/v4/jobdetails"

_DEBUG_FIELDS_PRINTED = False  # prints the first job record's field names once, for troubleshooting
_DEBUG_DETAILS_PRINTED = False  # prints the first jobdetails response's field names once, for troubleshooting

KEYWORDS = [
    "Online Marketing",
    "Digital Marketing",
    "SEO",
    "SEA",
    "Performance Marketing",
    "Social Media Marketing",
    "Content Marketing",
    "Marketing Manager",
    "Digital Marketing Manager",
    "Online Marketing Manager",
]

WORKTIME_LABELS = {
    "VOLLZEIT": "Vollzeit",
    "TEILZEIT": "Teilzeit",
    "HEIM_TELEARBEIT": "Homeoffice",
    "MINIJOB": "Minijob",
}

# Only postings published within the last N days are requested from the API,
# and MIN_PUBLISHED_DATE is a second safety-net filter applied again during
# cleaning (in case the API parameter doesn't fully catch everything).
PUBLISHED_WITHIN_DAYS = 30
MIN_PUBLISHED_DATE = "2026-07-01"

FINAL_COLUMNS = [
    "refnr", "titel", "arbeitgeber", "city", "zip", "bundesland",
    "published", "_keyword", "level", "employment_type",
    "hard_skills", "soft_skills", "skill_descriptions",
]

# Keyword patterns used to detect seniority level from title/description
LEVEL_PATTERNS = {
    "Junior": r"\b(junior|einsteiger|berufseinsteiger|trainee|werkstudent|praktikant)\b",
    "Senior": r"\b(senior|erfahren|lead|leiter|leitung|head\s+of|teamleiter)\b",
    "Middle": r"\b(mid[- ]?level|erfahrung\s+von\s+\d|mehrjährige\s+erfahrung)\b",
}

# Skill dictionaries used to extract structured skills out of the free-text
# job description. Key = label written into the output table.
HARD_SKILLS_DE = {
    "SEO": r"\bseo\b",
    "SEA": r"\bsea\b",
    "Google Ads": r"google\s*ads|google\s*adwords",
    "Google Analytics": r"google\s*analytics",
    "Meta Ads": r"meta\s*ads|facebook\s*ads",
    "Social Media Advertising": r"social[- ]media[- ]ads|social[- ]media[- ]advertising",
    "Content Management System": r"\bcms\b|content[- ]management[- ]system|wordpress|typo3",
    "Email Marketing": r"e-?mail[- ]marketing|newsletter[- ]marketing",
    "HTML/CSS": r"\bhtml\b|\bcss\b",
    "Photoshop": r"photoshop",
    "Adobe Creative Suite": r"adobe\s*(creative\s*(cloud|suite)|photoshop|illustrator|indesign)",
    "Excel": r"\bexcel\b",
    "Marketing Automation": r"marketing[- ]automation|hubspot|marketo",
    "CRM": r"\bcrm\b|salesforce",
    "Copywriting": r"copywriting|texterstellung",
    "A/B Testing": r"a\/b[- ]test",
    "Data Analytics": r"datenanalyse|data\s*analytics|kpi[- ]analyse",
}

SOFT_SKILLS_DE = {
    "Communication skills": r"kommunikationsstärke|kommunikationsfähigkeit",
    "Team skills": r"teamfähigkeit|teamplayer|teamarbeit",
    "Creativity": r"kreativität|kreativ(?:e|es|er)?\b",
    "Initiative": r"eigeninitiative|selbstständige\s+arbeitsweise|eigenverantwortlich",
    "Analytical thinking": r"analytisches\s+denken|analytische(?:s|r)?\s+fähigkeiten",
    "Organizational skills": r"organisationstalent|organisationsfähigkeit",
    "Resilience": r"belastbarkeit|stressresistent",
    "Flexibility": r"flexibilität|flexibel",
    "Negotiation skills": r"verhandlungsgeschick",
    "Time management": r"zeitmanagement|priorisierungsfähigkeit",
}


# ---------------------------------------------------------------------------
# STEP 1. SEARCH JOB POSTINGS
# ---------------------------------------------------------------------------

def search_jobs(keyword, page_size=100, max_pages=50, pause=0.3):
    """
    Paginates through all job postings for one keyword.
    No 'wo' (location) parameter is sent, so the search covers all of
    Germany. angebotsart=1 restricts results to regular jobs (excludes
    apprenticeships / internships).
    """
    results = []
    page = 1
    global _DEBUG_FIELDS_PRINTED

    while page <= max_pages:
        params = {
            "was": keyword,
            "angebotsart": 1,
            "veroeffentlichtseit": PUBLISHED_WITHIN_DAYS,
            "page": page,
            "size": page_size,
        }
        response = requests.get(SEARCH_URL, headers=HEADERS, params=params, timeout=20)

        if response.status_code != 200:
            print(f"  [!] {keyword} - page {page}: status {response.status_code}, stopping")
            print(f"      response text: {response.text[:300]}")
            break

        data = response.json()
        postings = data.get("ergebnisliste", [])

        if not postings:
            if page == 1:
                # diagnostic output for the first empty page, so we can see
                # what the API actually sent back instead of guessing
                print(f"  [debug] {keyword}: 0 postings. maxErgebnisse={data.get('maxErgebnisse')!r}, "
                      f"top-level keys={list(data.keys())}")
            break

        for job in postings:
            if not _DEBUG_FIELDS_PRINTED:
                print(f"  [debug] first record fields: {list(job.keys())}")
                _DEBUG_FIELDS_PRINTED = True

            # City/zip/bundesland are fetched later from job details
            # (the 'arbeitsorte' field there is well-documented and reliable;
            # the search result's own location field is not).
            results.append({
                "refnr": job.get("referenznummer") or job.get("refnr"),
                "titel": job.get("stellenangebotsTitel") or job.get("hauptberuf"),
                "arbeitgeber": job.get("firma"),
                "published": job.get("datumErsteVeroeffentlichung") or job.get("aenderungsdatum"),
                "_keyword": keyword,
            })

        # fewer results than the page size means this was the last page
        if len(postings) < page_size:
            break

        page += 1
        time.sleep(pause)  # delay between requests to be a polite API client

    return results


def collect_all(keywords):
    """Collects job postings for every keyword and merges them into one DataFrame."""
    all_rows = []

    for kw in keywords:
        print(f"Collecting: {kw}")
        rows = search_jobs(kw)
        print(f"  -> found {len(rows)}")
        all_rows.extend(rows)
        time.sleep(0.3)

    df = pd.DataFrame(all_rows, columns=[
        "refnr", "titel", "arbeitgeber", "published", "_keyword",
    ])
    print(f"\nTotal collected (keyword overlaps included): {len(df)}")
    return df


# ---------------------------------------------------------------------------
# STEP 2. ENRICH WITH DETAILS (DESCRIPTION, EMPLOYMENT TYPE)
# ---------------------------------------------------------------------------

def get_job_details(refnr, pause=0.2):
    """
    Fetches the detail page for one job posting by refnr.
    The refnr has to be base64-encoded before it can be used in the URL.
    Returns a dict with the raw description text (used later to extract
    skills and level), the employment type, and the location
    (city/zip/bundesland, taken from the 'arbeitsorte' field).
    """
    global _DEBUG_DETAILS_PRINTED
    empty = {"description": "", "employment_type": "", "city": "", "zip": "", "bundesland": ""}

    try:
        encoded_refnr = base64.b64encode(refnr.encode()).decode()
        response = requests.get(f"{DETAILS_URL}/{encoded_refnr}", headers=HEADERS, timeout=20)
        time.sleep(pause)

        if response.status_code != 200:
            if not _DEBUG_DETAILS_PRINTED:
                print(f"  [debug] jobdetails request failed: status {response.status_code}, "
                      f"body: {response.text[:300]}")
                _DEBUG_DETAILS_PRINTED = True
            return empty

        data = response.json()

        if not _DEBUG_DETAILS_PRINTED:
            print(f"  [debug] jobdetails fields: {list(data.keys())}")
            _DEBUG_DETAILS_PRINTED = True

        description = (
            data.get("stellenangebotsBeschreibung")
            or data.get("stellenbeschreibung")
            or ""
        )

        # employment type can be a list of codes (VOLLZEIT, TEILZEIT, ...)
        arbeitszeiten = data.get("arbeitszeitmodelle", []) or []
        employment_type = ", ".join(
            WORKTIME_LABELS.get(code, code) for code in arbeitszeiten
        )

        # location: 'arbeitsorte' is a list, take the first entry
        arbeitsorte = data.get("arbeitsorte") or []
        first_ort = arbeitsorte[0] if arbeitsorte else {}

        return {
            "description": description,
            "employment_type": employment_type,
            "city": first_ort.get("ort") or "",
            "zip": first_ort.get("plz") or "",
            "bundesland": first_ort.get("region") or "",
        }

    except requests.RequestException:
        return empty


def enrich_with_details(df):
    """
    For every job in df, fetches the full description (skill_descriptions),
    employment type, and location (city/zip/bundesland), matched by refnr.
    """
    if df.empty:
        print("No jobs to enrich - the search step returned 0 results.")
        df = df.copy()
        for col in ["skill_descriptions", "employment_type", "city", "zip", "bundesland"]:
            df[col] = []
        return df

    details = []

    total = len(df)
    for i, refnr in enumerate(df["refnr"], start=1):
        if i % 25 == 0 or i == total:
            print(f"  Details: {i}/{total}")

        details.append(get_job_details(refnr))

    df = df.copy()
    df["skill_descriptions"] = [d["description"] for d in details]
    df["employment_type"] = [d["employment_type"] for d in details]
    df["city"] = [d["city"] for d in details]
    df["zip"] = [d["zip"] for d in details]
    df["bundesland"] = [d["bundesland"] for d in details]
    return df


# ---------------------------------------------------------------------------
# STEP 3. EXTRACT LEVEL AND SKILLS FROM TEXT
# ---------------------------------------------------------------------------

def extract_level(titel, description):
    """
    Detects seniority level (Junior / Middle / Senior) from title and
    description. Leaves it blank if nothing matches - no guessing.
    """
    text = f"{titel or ''} {description or ''}".lower()

    for level, pattern in LEVEL_PATTERNS.items():
        if re.search(pattern, text, flags=re.IGNORECASE):
            return level

    return ""


def extract_skills(description, skill_dict):
    """
    Matches the description text against a skill dictionary (one regex per
    skill) and returns all matched skills joined by a comma.
    """
    if not description:
        return ""

    text = description.lower()
    found = [
        label for label, pattern in skill_dict.items()
        if re.search(pattern, text, flags=re.IGNORECASE)
    ]
    return ", ".join(found)


# ---------------------------------------------------------------------------
# STEP 4. CLEANING
# ---------------------------------------------------------------------------

def clean_jobs(df):
    """
    - removes exact duplicates by refnr
    - removes rows without a title or without a description
    - keeps only postings published on/after MIN_PUBLISHED_DATE (safety net;
      the API's own 'veroeffentlichtseit' filter already restricts this
      during collection, this just double-checks it)
    - removes *logical* duplicates: the same employer reposting the exact
      same title over and over under a different refnr - keeps the most
      recently published copy of each (employer, title) pair
    - normalizes whitespace in text columns
    - adds level, hard_skills, soft_skills based on skill_descriptions
    """
    df = df.copy()

    df = df.drop_duplicates(subset="refnr")
    df = df.dropna(subset=["titel", "refnr"])
    df = df[df["skill_descriptions"].astype(str).str.strip().astype(bool)]

    for col in ["titel", "arbeitgeber", "city", "bundesland"]:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip()

    # safety-net date filter
    published_dt = pd.to_datetime(df["published"], errors="coerce")
    df = df[published_dt >= pd.Timestamp(MIN_PUBLISHED_DATE)]
    published_dt = published_dt[df.index]

    # logical dedup: same employer + same title posted repeatedly.
    # sort so the newest posting comes first, then keep only the first
    # occurrence of each (employer, title) combination.
    df = df.assign(_published_dt=published_dt)
    df = df.sort_values("_published_dt", ascending=False)
    dedup_key = (
        df["arbeitgeber"].str.lower().str.strip() + "||" +
        df["titel"].str.lower().str.strip()
    )
    df = df[~dedup_key.duplicated(keep="first")]
    df = df.drop(columns="_published_dt")

    df["level"] = df.apply(
        lambda row: extract_level(row["titel"], row["skill_descriptions"]), axis=1
    )
    df["hard_skills"] = df["skill_descriptions"].apply(
        lambda text: extract_skills(text, HARD_SKILLS_DE)
    )
    df["soft_skills"] = df["skill_descriptions"].apply(
        lambda text: extract_skills(text, SOFT_SKILLS_DE)
    )

    return df.reset_index(drop=True)


def select_final_columns(df):
    """Keeps only the columns from FINAL_COLUMNS, in the given order."""
    for col in FINAL_COLUMNS:
        if col not in df.columns:
            df[col] = ""
    return df[FINAL_COLUMNS]


# ---------------------------------------------------------------------------
# STEP 5. SAVE
# ---------------------------------------------------------------------------

def save_excel(df, path):
    """
    Save as .xlsx instead of .csv. This sidesteps two problems entirely:
    - no delimiter guessing (Excel sometimes assumes ',' even when the
      file uses ';', which splits nested-dict text like arbeitsort across
      the wrong columns)
    - no encoding issues with German umlauts (ä, ö, ü, ß) - .xlsx stores
      text natively, there is no CSV encoding/BOM to get wrong
    Requires openpyxl (already installed in Google Colab by default).
    """
    df.to_excel(path, index=False, engine="openpyxl")


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    raw = collect_all(KEYWORDS)
    raw = enrich_with_details(raw)
    save_excel(raw, "jobs_raw.xlsx")

    clean = clean_jobs(raw)
    final = select_final_columns(clean)
    save_excel(final, "jobs_clean.xlsx")

    print(f"Cleaned: {len(final)} rows -> jobs_clean.xlsx")